export const metadata = {
  title: 'Privacy Policy — ReplyRocket',
  description: 'How ReplyRocket collects, uses, and protects your data.',
}

const COMPANY = 'MyBSolutions Pvt Ltd'
const BRAND = 'ReplyRocket'
const SUPPORT_EMAIL = 'support@mybsolutions.in'
const PRIVACY_EMAIL = 'privacy@mybsolutions.in'
const UPDATED = 'May 11, 2026'

export default function PrivacyPage() {
  return (
    <Shell title="Privacy Policy" updated={UPDATED}>
      <p>
        This Privacy Policy describes how {COMPANY} (&quot;{COMPANY}&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;)
        collects, uses, stores, shares, and protects information when you use {BRAND} (the &quot;Service&quot;) accessible at this
        website and the related applications, APIs, and integrations.
      </p>
      <p>
        By using the Service you agree to this Policy. If you do not agree, do not use the Service.
      </p>

      <H2>1. Who we are</H2>
      <p>
        {COMPANY}, a company registered in India, operates {BRAND}. The {COMPANY} entity is the
        &quot;Data Fiduciary&quot; under India&apos;s Digital Personal Data Protection Act, 2023 (DPDPA) for personal data we
        process about you.
      </p>

      <H2>2. Information we collect</H2>
      <H3>2.1 Information you provide to us</H3>
      <Ul>
        <li><b>Account data</b> &mdash; name, email, password (stored as a bcrypt hash, never in plaintext), business name.</li>
        <li><b>AI agent configuration</b> &mdash; persona text, tone, language, FAQs, service/pricing list, booking link, UPI ID, payment-link defaults that you enter into the AI Agent page.</li>
        <li><b>Campaign content</b> &mdash; post captions, post images, keywords, DM templates.</li>
        <li><b>Conversation content</b> &mdash; messages you send and receive through the Service.</li>
      </Ul>

      <H3>2.2 Information from connected Instagram accounts (when you Connect Instagram)</H3>
      <Ul>
        <li>Your Instagram user ID, username, account type, and profile picture URL.</li>
        <li>A long-lived (60-day) access token issued by Meta that the Service stores encrypted at rest and uses solely to act on your behalf within the scopes you granted.</li>
        <li><b>Inbound comments and direct messages</b> on the Instagram media you own, delivered to us by Meta via webhook. We only receive events for media and threads associated with your connected account.</li>
        <li>The Service writes <i>back</i> to Instagram as you (auto-replies to comments, sending DMs) only based on rules you configure in the AI Agent and Campaigns pages.</li>
      </Ul>

      <H3>2.3 Information from third-party payment processors</H3>
      <Ul>
        <li>When a payment link generated by ReplyRocket is paid, Razorpay sends us a signed webhook containing the payment amount, payment status, payment ID, and a reference ID we created to associate the payment with the originating conversation. We do not see, receive, or store card numbers, CVVs, UPI PINs, or other sensitive payment instruments — Razorpay handles those directly.</li>
      </Ul>

      <H3>2.4 Information collected automatically</H3>
      <Ul>
        <li>Standard server logs &mdash; IP address, browser user-agent, timestamps, and request paths &mdash; retained for up to 30 days for security and abuse-detection purposes.</li>
        <li>Authentication cookies (httpOnly, sameSite=lax, secure) holding a signed JWT for up to 7 days.</li>
      </Ul>

      <H2>3. How we use information</H2>
      <Ul>
        <li>Provide, operate, and maintain the Service.</li>
        <li>Authenticate you and protect your workspace from unauthorized access.</li>
        <li>Process Instagram comments and messages on your behalf in accordance with rules you configure, including generating AI-powered replies via the Claude API operated by Anthropic.</li>
        <li>Generate Razorpay payment links on your behalf and reconcile incoming payment events.</li>
        <li>Investigate abuse, fraud, and security incidents.</li>
        <li>Comply with applicable law and respond to lawful government requests.</li>
      </Ul>
      <p>
        We <b>do not</b> sell your personal data. We <b>do not</b> use Instagram message content, comments, or any
        connected-account data for advertising or to train third-party machine learning models. AI responses are
        generated on the fly by the Anthropic Claude API; Anthropic&apos;s zero-retention API endpoint is used where supported.
      </p>

      <H2>4. Who we share information with</H2>
      <Ul>
        <li><b>Sub-processors</b> who help us run the Service: MongoDB Atlas (database hosting), Vercel (application hosting), Anthropic (AI inference), Meta Platforms (Instagram Graph API), Razorpay (payment processing). These vendors are bound by contractual confidentiality and data-protection commitments.</li>
        <li><b>Law enforcement / legal</b> where required by valid Indian law or court order.</li>
        <li><b>Business transfers</b> &mdash; if {COMPANY} is acquired, merged, or sells the Service, your data may be transferred to the acquirer subject to this Policy.</li>
      </Ul>

      <H2>5. International data transfers</H2>
      <p>
        Some of our sub-processors (e.g. Anthropic, Vercel) operate servers outside India. Where required by DPDPA, we
        ensure adequate contractual protections are in place.
      </p>

      <H2>6. Data retention</H2>
      <Ul>
        <li>Account, agent, campaign, conversation, and lead data &mdash; retained for as long as your account is active, and for up to 30 days after account deletion (for backup rotation), after which it is permanently deleted.</li>
        <li>Instagram access tokens &mdash; deleted immediately when you disconnect Instagram or delete your account.</li>
        <li>Server logs &mdash; up to 30 days.</li>
        <li>Webhook event records &mdash; up to 90 days for debugging.</li>
      </Ul>

      <H2>7. Your rights under DPDPA</H2>
      <p>You have the right to:</p>
      <Ul>
        <li><b>Access</b> the personal data we hold about you.</li>
        <li><b>Correct or update</b> inaccurate data &mdash; most fields are editable from inside the app.</li>
        <li><b>Erase</b> your data by deleting your account or requesting deletion at {PRIVACY_EMAIL}.</li>
        <li><b>Withdraw consent</b> at any time by disconnecting Instagram (Settings → Instagram → Disconnect) or by deleting your account.</li>
        <li><b>Nominate</b> another person to exercise rights on your behalf in the event of death or incapacity (DPDPA Sec. 14).</li>
        <li><b>Lodge a grievance</b> with us by emailing {PRIVACY_EMAIL}. If unresolved, you may approach the Data Protection Board of India.</li>
      </Ul>

      <H2>8. Instagram-specific data deletion</H2>
      <p>
        If you remove ReplyRocket from your Instagram account&apos;s authorized apps list (Instagram Settings → Apps and
        websites → ReplyRocket → Remove), Meta notifies our deauthorization endpoint. Within 24 hours we delete the
        stored Instagram access token and disable inbound webhook processing for your account. Conversation history and
        leads are retained unless you also delete your ReplyRocket account.
      </p>
      <p>
        To request full deletion of Instagram-derived data while keeping your ReplyRocket account, email {PRIVACY_EMAIL}
        with the subject line &quot;Instagram data deletion&quot; from the email address on your ReplyRocket account.
        See also the <a href="/data-deletion" className="text-violet-600 hover:underline">Data Deletion Instructions</a>.
      </p>

      <H2>9. Security</H2>
      <Ul>
        <li>Passwords stored as bcrypt hashes (cost factor 10).</li>
        <li>JWT cookies are httpOnly, sameSite=lax, secure-only.</li>
        <li>All authenticated routes are scoped to the workspace and isolated from other tenants.</li>
        <li>Razorpay and Meta webhooks are verified using HMAC-SHA256 signatures over the raw request body.</li>
        <li>Access tokens are stored in our database and accessed only by authorized server-side code paths.</li>
      </Ul>

      <H2>10. Children</H2>
      <p>
        The Service is not directed to individuals under the age of 18. We do not knowingly collect data from children.
        If you believe a child has provided us data, email {PRIVACY_EMAIL} and we will delete it.
      </p>

      <H2>11. Changes to this Policy</H2>
      <p>
        We may update this Policy from time to time. The &quot;Last updated&quot; date at the top reflects the current version.
        Material changes will be announced in-product or via email.
      </p>

      <H2>12. Contact</H2>
      <p>
        Questions, complaints, or DPDPA requests:<br />
        <b>Privacy contact:</b> <a className="text-violet-600 hover:underline" href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a><br />
        <b>General support:</b> <a className="text-violet-600 hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a><br />
        <b>Company:</b> {COMPANY}, India
      </p>
    </Shell>
  )
}

function Shell({ title, updated, children }) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-violet-50/40 to-fuchsia-50/30">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <a href="/" className="text-violet-600 hover:underline text-sm">&larr; Back to ReplyRocket</a>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 mt-4 mb-2">{title}</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: {updated}</p>
        <article className="prose prose-slate max-w-none text-slate-700 leading-relaxed space-y-3 [&_h2]:mt-8 [&_h2]:mb-2 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-slate-900 [&_h3]:mt-4 [&_h3]:mb-1 [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-slate-800 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:my-2 [&_li]:my-1">
          {children}
        </article>
      </div>
    </div>
  )
}

function H2({ children }) { return <h2>{children}</h2> }
function H3({ children }) { return <h3>{children}</h3> }
function Ul({ children }) { return <ul>{children}</ul> }
