export const metadata = {
  title: 'Terms of Service — ReplyRocket',
  description: 'Terms governing your use of ReplyRocket.',
}

const COMPANY = 'MyBSolutions Pvt Ltd'
const BRAND = 'ReplyRocket'
const SUPPORT_EMAIL = 'support@mybsolutions.in'
const JURISDICTION = 'the courts of Hyderabad, Telangana, India'
const UPDATED = 'May 11, 2026'

export default function TermsPage() {
  return (
    <Shell title="Terms of Service" updated={UPDATED}>
      <p>
        These Terms of Service (&quot;Terms&quot;) form a binding agreement between you (&quot;you&quot;, &quot;Customer&quot;) and
        {' '}{COMPANY} (&quot;{COMPANY}&quot;, &quot;we&quot;, &quot;us&quot;) governing your use of {BRAND} (the &quot;Service&quot;).
        By creating an account or using the Service, you accept these Terms.
      </p>

      <H2>1. Eligibility</H2>
      <p>You must be at least 18 years old and legally capable of entering contracts under Indian law to use the Service.</p>

      <H2>2. Your account</H2>
      <Ul>
        <li>You are responsible for safeguarding your password and for any activity on your account.</li>
        <li>You must provide accurate information and keep it updated.</li>
        <li>Each account is for a single business or individual unless you have a paid multi-seat plan with us.</li>
        <li>You must not share account credentials.</li>
      </Ul>

      <H2>3. Acceptable use</H2>
      <p>You agree not to:</p>
      <Ul>
        <li>Send unsolicited messages (spam) in violation of Meta Platforms Terms, Instagram Community Guidelines, or applicable anti-spam laws.</li>
        <li>Use the Service to harass, defame, or harm any person.</li>
        <li>Reverse engineer, decompile, or attempt to derive source code of the Service.</li>
        <li>Resell, sublicense, or white-label the Service without our written permission.</li>
        <li>Circumvent rate limits, security controls, or workspace isolation.</li>
        <li>Use the Service for unlawful, fraudulent, or misleading commercial activity.</li>
      </Ul>

      <H2>4. Instagram integration</H2>
      <p>
        When you connect an Instagram account to the Service, you confirm you are the rightful owner or authorized operator
        of that account, and you authorize {BRAND} to read incoming comments and messages, send replies on your behalf,
        and create payment links in the Razorpay account you configure &mdash; all strictly within the Meta-granted scopes
        and the rules you set inside the Service.
      </p>
      <p>
        Your use of the Service is in addition to your obligations under the Meta Platforms Terms of Service, the
        Instagram Terms of Use, and the Instagram Platform Policy. We may suspend or remove functionality if required by
        Meta or to comply with their policies.
      </p>

      <H2>5. Payments</H2>
      <Ul>
        <li>Payment links generated by the Service are issued through Razorpay using the API keys you configure. Funds settle into your Razorpay account, not ours.</li>
        <li>{COMPANY} is not a party to any transaction between you and your customers and is not responsible for refunds, disputes, or chargebacks. These are governed by your Razorpay account terms.</li>
        <li>Service subscription fees (if any) are billed in Indian Rupees, inclusive of GST as applicable. Charges are non-refundable except where required by law.</li>
      </Ul>

      <H2>6. AI-generated content</H2>
      <p>
        Replies and recommendations produced by the Service are generated by large language models (Anthropic Claude). The
        models can produce inaccurate, biased, or unexpected output. You are responsible for reviewing AI output before it
        is sent, configuring the AI Agent prompt appropriately, and complying with all applicable laws regarding
        statements made to your customers.
      </p>

      <H2>7. Intellectual property</H2>
      <Ul>
        <li>The Service, including all code, design, trademarks, and documentation, is owned by {COMPANY} and licensed (not sold) to you for use during your account&apos;s active period.</li>
        <li>Content you upload or generate inside your workspace (campaigns, agent persona, messages) remains your property. You grant us a worldwide, non-exclusive license to host, process, and display that content solely to operate the Service for you.</li>
      </Ul>

      <H2>8. Service availability</H2>
      <p>
        We strive to keep the Service available 24/7 but do not guarantee any uptime or service level unless explicitly
        committed in a written enterprise agreement. We may perform maintenance with reasonable notice. Third-party
        outages (Meta, Razorpay, Anthropic) are outside our control.
      </p>

      <H2>9. Disclaimers</H2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT
        WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, OR NON-INFRINGEMENT.
      </p>

      <H2>10. Limitation of liability</H2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, {COMPANY}&apos;S TOTAL LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS
        OR YOUR USE OF THE SERVICE IS LIMITED TO THE AMOUNT YOU PAID US (IF ANY) IN THE 3 MONTHS PRECEDING THE EVENT
        GIVING RISE TO THE CLAIM. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.
      </p>

      <H2>11. Indemnification</H2>
      <p>
        You will indemnify and hold {COMPANY} harmless from any claim arising out of (a) your breach of these Terms,
        (b) content you send through the Service, (c) your misuse of any third-party service connected through the Service,
        or (d) your violation of Meta or Razorpay terms.
      </p>

      <H2>12. Termination</H2>
      <Ul>
        <li>You may close your account at any time from Settings, or by emailing {SUPPORT_EMAIL}.</li>
        <li>We may suspend or terminate your account if you breach these Terms, abuse the Service, or place the Service at legal or operational risk.</li>
        <li>On termination, access to the Service ceases. We retain backup copies of data for up to 30 days for operational reasons before final deletion.</li>
      </Ul>

      <H2>13. Governing law and venue</H2>
      <p>
        These Terms are governed by the laws of India. Any dispute is subject to the exclusive jurisdiction of {JURISDICTION}.
      </p>

      <H2>14. Changes to these Terms</H2>
      <p>
        We may update these Terms. Material changes will be announced in-product or via email. Continued use of the
        Service after changes constitutes acceptance.
      </p>

      <H2>15. Contact</H2>
      <p>
        Questions about these Terms: <a className="text-violet-600 hover:underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a><br />
        Company: {COMPANY}, India
      </p>
    </Shell>
  )
}

function Shell({ title, updated, children }) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-violet-50/40 to-fuchsia-50/30">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <a href="/" className="text-violet-600 hover:underline text-sm">&larr; Back to ReplyRocket</a>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 mt-4 mb-2">{title}</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: {updated}</p>
        <article className="prose prose-slate max-w-none text-slate-700 leading-relaxed space-y-3 [&_h2]:mt-8 [&_h2]:mb-2 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-slate-900 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:my-2 [&_li]:my-1">
          {children}
        </article>
      </div>
    </div>
  )
}

function H2({ children }) { return <h2>{children}</h2> }
function Ul({ children }) { return <ul>{children}</ul> }
